springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
azure:
  application-insights:
    connection-string: InstrumentationKey=e526f19c-54fc-4a5d-ae6f-0036ff702711;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=5d57ddf6-cc5f-410a-b491-f8af806a305c
